version: 1.0.{build}
image: Visual Studio 2017
nuget:
  project_feed: true
build:
  verbosity: minimal
test: off
deploy:
- provider: NuGet
  api_key:
    secure: BUg/2zGAM0ydp1SSFKmKefvVud41TomH1PQSZ9u/ZMEIqQKHisuCLEOSPNbzNRrd
  skip_symbols: true
